# Generated by Django 5.1.6 on 2025-02-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('eventCATAGORY', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField(blank=True, max_length=100, null=True)),
                ('numberofParticipant', models.IntegerField(blank=True, null=True)),
                ('eventposter', models.ImageField(blank=True, null=True, upload_to='eventposter/')),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('notification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='report/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventmodel')),
            ],
        ),
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(blank=True, max_length=100, null=True)),
                ('acheivement', models.CharField(blank=True, max_length=100, null=True)),
                ('jornalname', models.CharField(blank=True, max_length=100, null=True)),
                ('yearofpublication', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('internship', models.CharField(blank=True, max_length=100, null=True)),
                ('internshipdate', models.DateField(blank=True, null=True)),
                ('internshipvenue', models.CharField(blank=True, max_length=100, null=True)),
                ('internshipcertificate', models.ImageField(blank=True, null=True, upload_to='workshopcertificate/')),
                ('conferencename', models.CharField(blank=True, max_length=100, null=True)),
                ('dateofconference', models.DateField(blank=True, null=True)),
                ('conferencevenue', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('seminarorwebinarname', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('seminardate', models.DateField(blank=True, null=True)),
                ('seminarcertificate', models.ImageField(blank=True, null=True, upload_to='seminarcertificate')),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='resultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventmodel')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='complaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='teacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(blank=True, max_length=100, null=True)),
                ('facultyacheivement', models.CharField(blank=True, max_length=100, null=True)),
                ('jornalname', models.CharField(blank=True, max_length=100, null=True)),
                ('yearofpublication', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('workshopname', models.CharField(blank=True, max_length=100, null=True)),
                ('workshopdate', models.DateField(blank=True, null=True)),
                ('workshopvenue', models.CharField(blank=True, max_length=100, null=True)),
                ('workshopcertificate', models.ImageField(blank=True, null=True, upload_to='workshopcertificate/')),
                ('conferencename', models.CharField(blank=True, max_length=100, null=True)),
                ('dateofconference', models.DateField(blank=True, null=True)),
                ('conferencevenue', models.CharField(blank=True, max_length=100, null=True)),
                ('conferencecertificate', models.ImageField(blank=True, null=True, upload_to='conferencecertificate/')),
                ('seminarorwebinarname', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('seminardate', models.DateField(blank=True, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificate')),
                ('departmentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departmentmodel')),
            ],
        ),
    ]
