# Generated by Django 5.1.6 on 2025-02-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='acheivement',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='conferencename',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='conferencevenue',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='dateofconference',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='internshipcertificate',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='internshipdate',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='internshipvenue',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='jornalname',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='seminarcertificate',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='seminardate',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='seminarorwebinarname',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='yearofpublication',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='conferencecertificate',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='conferencename',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='conferencevenue',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='dateofconference',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='facultyacheivement',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='jornalname',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='seminardate',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='seminarorwebinarname',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='workshopcertificate',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='workshopdate',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='workshopname',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='workshopvenue',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='yearofpublication',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='admissionnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='LOGIN_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.loginmodel'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Student_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogory', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('STUDENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogory', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('TEACHERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teachermodel')),
            ],
        ),
    ]
