# Generated by Django 5.1.6 on 2025-02-19 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_studentmodel_acheivement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='DEPT_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmentmodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='Teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teachermodel'),
        ),
    ]
